#!/usr/bin/env bash
# is a factors challenge

check_factor()
{
	if [ $# -ne 3 ];
        then
                s=("$@")
                x=0
                n2=1
                for a in ${s[*]};
                do
                        if [ $x -gt 1 ];
                        then
                                n2=$(echo $a*$n2 | bc)
                        fi
                        x=$((x + 1))
                done
        else
                n2=$3
        fi

        n1=$2
        n=$(echo "$1" | tr ':' '=')

        result=$(echo "if($n2 > $n1) 1 else 0" | bc)
	        if ((result == 1)); then
		        nn=$n1
		        n1=$n2
		        n2=$nn
                fi

        echo "$n$n1*$n2"
}

if [ $# -ne 1 ]
then
        echo 'Usage: factors <file>'
        exit 1
else

        while read i
        do

                result=$(factor "$i")
                check_factor $result

        done < "$1"
fi
