#!/usr/bin/python3


import sys
import time


def factorize(a):
    '''Takes a number as input.
    Args:
        num: input integer.
        Return: A tuple of two factors if the number is not a prime.
                None if the number is prime.
    '''
    for z in range(2, int(a**0.5)+1):
        if a % z == 0:
            return (z, a//z)
    return None


if __name__ == "__main__":


    '''Reads the input file.
    '''
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        exit()


    input_file = sys.argv[1]


    try:
        with open(input_file, 'r') as ff:
            ll = ff.readlines()
    except FileNotFoundError:
        print("File not found")
        exit()


    start_time = time.time()


    '''loops over each line (which should contain one natural number per line),
        and calls factorize on each number.
        If factorize returns a tuple of factors,
        it prints the factorization in the desired forma
    '''
    for l in ll:
        a = int(l.strip())
        factors = factorize(a)
        if factors:
            print(f"{a}={factors[0]}*{factors[1]}")


        '''If the elapsed time exceeds 5 seconds,
            the program exits with an error message.
        '''
        if time.time() - start_time > 5:
            print("Time limit exceeded")
            exit()
