#!/usr/bin/python3


import sys
import random
import time


def is_prime(b, k=20):
    '''
    '''
    if b == 2 or b == 3:
        return True
    if b < 2 or b % 2 == 0:
        return False


    d = b - 1
    r = 0
    while d % 2 == 0:
        d //= 2
        r += 1


    for _ in range(k):
        a = random.randint(2, b - 2)
        x = pow(a, d, b)
        if x == 1 or x == b - 1:
            continue
        for _ in range(r - 1):
            x = pow(x, 2, b)
            if x == b - 1:
                break
        else:
            return False


    return True


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: rsa <file>")
        exit()


    input_file = sys.argv[1]


    try:
        with open(input_file, 'r') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print("File not found")
        exit()


    start_time = time.time()


    b = int(lines[0].strip())


    for i in range(2, b//2):
        if b % i == 0 and is_prime(i) and is_prime(b//i):
            print(f"{b}={i}*{b//i}")
            break


        if time.time() - start_time > 5:
            print("Time limit exceeded")
            exit()
